#!/bin/sh
ssh jenkins@192.168.0.70 <<EOF
    cd ~/workspace/project-backend		
    git pull origin release
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.13.0
    npm install -g yarn
    yarn global add typescript ts-node pm2 nodemon
    rm -rf dist
    yarn build
    cp ~/ca.crt dist
    cp ~/cert.crt dist
    cp ~/private.key dist
    pm2 restart ecosystem.config.js
    exit
EOF